version: "3"
services:
  app:
    container_name: countrycodeApp
    build: .
    environment:
      - PROD=true
    depends_on:
      - mongo
    ports:
      - "5000:5000"

  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"
